Ac 28 - Like Event
ThomassenMichiel/AcaraFrontend pull request #37
Opened 2020-05-03 10:26 UTC by TomHaeldermans94

2020-05-03 15:12 UTC, ThomassenCathleia requested changes

2020-05-03 15:12 UTC, ThomassenCathleia commented on src/main/java/be/acara/frontend/service/UserServiceImpl.java
> +        }
I'm going to nitpick here: keep the else on the same line als the closing curly bracket

2020-05-03 15:12 UTC, ThomassenCathleia commented on src/test/java/be/acara/frontend/controller/EventControllerTest.java
> +    void findAllEventsWithAnonymousUser() throws Exception {
rename method  to `findAllEvents_withAnonymousUser()`

add @WithAnonymousUser to the method signature

2020-05-03 15:12 UTC, ThomassenCathleia commented on src/test/java/be/acara/frontend/controller/EventControllerTest.java
> +    void findAllEventsWithUser() throws Exception {
rename method to `findAllEvents_withUser()`

2020-05-03 15:12 UTC, ThomassenCathleia commented on src/main/resources/templates/eventList.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous
Curious why the version needed to be changed? 🤔

2020-05-03 15:12 UTC, ThomassenCathleia commented on src/main/java/be/acara/frontend/controller/EventController.java
> +        }
The following will achieve the same
```
if (SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken) {
 }
```

2020-05-03 15:12 UTC, ThomassenCathleia commented on src/main/java/be/acara/frontend/controller/EventController.java
> +        }
The following will achieve the same
```
if (SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken) {
 }
```

2020-05-03 15:12 UTC, ThomassenMichiel commented on src/main/java/be/acara/frontend/controller/UserController.java
> +    }
```
private void addPageNumbers(EventDtoList events, ModelMap modelMap, String attribute) {
        if (events.getTotalPages() == 0) {
            return;
        }
        modelMap.addAttribute(attribute, IntStream.rangeClosed(1, events.getTotalPages())
                .boxed()
                .collect(Collectors.toList()));
    }
```

2020-05-03 15:12 UTC, ThomassenMichiel commented on src/main/java/be/acara/frontend/controller/UserController.java
> +        }
replace with method in comment below

2020-05-03 15:12 UTC, ThomassenMichiel commented on src/main/java/be/acara/frontend/controller/UserController.java
> +    }
We could put this in an util method? its almost generic enough to pull it off. 🤔

2020-05-04 12:36 UTC, sbottelbergs commented on src/main/java/be/acara/frontend/service/UserServiceImpl.java
> +        userFeignClient.dislikeEvent(id);
This id seems to map to `/api/users/{id}/events`, but you are giving it an event id. How does this work?
Remember: For API endpoint `/api/users/{id}/events`; `{id}` implies `{userId}`. A more correct API endpoint would be: `/api/users/{userId}/likes/{eventId}`

2020-05-04 12:38 UTC, sbottelbergs commented on src/main/java/be/acara/frontend/service/UserServiceImpl.java
> +        }
There is also an inconsistency with spaces: 
`if(doesUserLikeThisEvent(id)){` => `if (doesUserLikeThisEvent(id)) {`
```
}
        else{
```
=> 
```
} else {
```

2020-05-06 23:07 UTC, ThomassenCathleia requested changes

2020-05-06 23:07 UTC, ThomassenCathleia commented on src/main/java/be/acara/frontend/controller/dto/LikeEventDto.java
> +@Builder
Do we really need all these lombok annotations? A getter and the allargsconstructor should be more than enough.

2020-05-06 23:07 UTC, ThomassenCathleia commented on src/main/resources/templates/eventDetails.html
> +                    <span class="col-6 text-left" th:text="${event.eventDate.toString().substring(0,10)}">event date</span>
There is a better way of doing this. What date class did java 8 introduce?

2020-05-06 23:07 UTC, ThomassenCathleia commented on src/main/resources/templates/eventDetails.html
> +                    <span class="col-6 text-left" th:text="${event.eventDate.toString().substring(11)}">event date</span>
Same thing as for the date. Just time, not date this time. You also forgot the span content.

2020-05-06 23:07 UTC, ThomassenCathleia commented on src/main/resources/templates/eventDetails.html
> +                    <span class="col-6 text-left" th:text="${event.category.substring(0,1) + event.category.substring(1).toLowerCase()}">category</span>
If we are going to do this, we'd better put the category dto in event instead of a plain string.

2020-05-06 23:07 UTC, ThomassenCathleia commented on src/test/java/be/acara/frontend/controller/EventControllerTest.java
> +    void findAllEventsWithAnonymousUser() throws Exception {
Add @WithAnonymousUser
Add underscore like this `void findAllEvents_withAnonymousUser()`

2020-05-06 23:07 UTC, ThomassenCathleia commented on src/test/java/be/acara/frontend/controller/EventControllerTest.java
> +    void findAllEventsWithUser() throws Exception {
Add unscore to method name like the comment above

2020-05-06 23:08 UTC, ThomassenMichiel commented
Don't forget to merge with master and resolve conflicts.

2020-05-08 20:38 UTC, ThomassenCathleia approved these changes

2020-05-08 20:51 UTC, merged